// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using moneygram_api.Data;

#nullable disable

namespace moneygram_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250120104222_UpdateSendTransactionsWithMoreproperies")]
    partial class UpdateSendTransactionsWithMoreproperies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("moneygram_api.Models.ExceptionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExceptionMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExceptionLogs");
                });

            modelBuilder.Entity("moneygram_api.Models.RequestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Device")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResponseTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("moneygram_api.Models.SendTransaction", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<DateTime?>("AddDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Charge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Checker")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CommitDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Commited")
                        .HasColumnType("bit");

                    b.Property<string>("ConsumerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FormFree")
                        .HasColumnType("bit");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginatingCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Processed")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiveCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverAddress3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverCountryOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverDOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverLegalIDType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverPhotoIDCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverPhotoIDNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverPhotoIDState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverPhotoIDType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiverZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderAddress1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderAddress2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderAddress3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderCountryOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderDOB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderLegalIDType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPhotoIDCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPhotoIDNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPhotoIDState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderPhotoIDType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceOfFunds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Successful")
                        .HasColumnType("bit");

                    b.Property<string>("Surburb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TellerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionPurpose")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SendTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
